apify/covid-19

- japan/.gitignore
- japan/package.json
- japan/src/main.js
Fix for infected "floating" number
> fix - japan covid actor

- india/main.js
Extra rows from regions table were removed from output.
All numeric values are saved as numbers now.
> [India] fix regions data

- usa/src/main.js
Also commented some graph whi I wasnt able to repair.
> Changed selector to main numbers

- slovakia/INPUT_SCHEMA.json
- slovakia/src/main.js
I rewrite this actor to BasicActor
> fix - Slovakia data not actual #23

- poland/src/main.js
Remove space used as  thousand separator before parsing to Int
> Remove spaces before parseInt

- slovakia/.gitignore
- slovakia/src/main.js
Added additional available data from the source.
> Additional data for Slovakia scraper

- norway/package-lock.json
- norway/package.json
- norway/src/main.js
- russia/Dockerfile
- russia/package-lock.json
- russia/package.json
- russia/src/main.js
- world/src/transform-schema.json
> Multiple fixes

- brazil/package-lock.json
- brazil/package.json
- brazil/src/main.js
They changed the data endpoints, and now have recovered data
closes  #106
> update covid BR

- palestine/main.js
> fix Palestine

- brazil/src/main.js
* allow people to run on their own account from scratch
* closes #117
> change the checking logic for new data (BR)

- philippines/Dockerfile
- philippines/INPUT_SCHEMA.json
- philippines/main.js
- philippines/package-lock.json
- philippines/package.json
> fix - Phillipines actor not running

- norway/src/main.js
> Norway source changed

- algeria/src/main.js
> fix - Algeria times out

- czechia/src/main.js
> Added recoveredByRegionData

- slovenia/main.js
- slovenia/package-lock.json
- slovenia/package.json
> fix - Slovenia - wrong number

- japan/package.json
- japan/src/main.js
Added failed count for notification
> [japan] - add failed notification

- luxembourg/package-lock.json
- luxembourg/package.json
- luxembourg/src/main.js
> fix - Luxembourg

- czechia/src/idnes.js
- czechia/src/main.js
> czechia source changed

- malaysia/Dockerfile
- malaysia/main.js
> Malaysia - use simple http requests

- denmark/src/main.js
> fix - denmark not working

- spain/Dockerfile
- spain/main.js
- spain/package-lock.json
- spain/package.json
> spain - use PDF source

- spain/main.js
- spain/package-lock.json
- spain/package.json
> spain - add regions data

- czechia/package-lock.json
- czechia/package.json
- czechia/src/main.js
> czechia - add infected, recovered & deceased by region

- czechia/src/main.js
> czechia - update selectors & number parsing

- luxembourg/src/main.js
> luxembourg - use pdf source

- belgium/src/main.js
Tested column name changed from TEST to TEST_ALL.
> belgium - fix null tested value

- lithuania/main.js
- lithuania/package-lock.json
- lithuania/package.json
> lithuania - updated to basic crawler

- luxembourg/package-lock.json
- luxembourg/package.json
- luxembourg/src/main.js
> luxembourg - source changed to xlsx

- denmark/package-lock.json
- denmark/package.json
- denmark/src/main.js
> Denmark - source changed

- india/main.js
Great work on the project, but you didn't get the number of tests done on the previous day in the header section of the website https://www.mohfw.gov.in/ , so I just made a commit to add that. Hope you like it because I want to use this feature for a project that I am going to be making and it requires the number of test that are being done.
> Added feature to get the count of tests done on the previous day

- poland/src/main.js
Thish should fix https://github.com/apify/covid-19/issues/252
> Fix Poland crawler

- slovakia/src/main.js
delete and replace the same values of Bratislava and Košice
> Slovakia small fix

- poland/src/main.js
Recently the api was changed, somebody updated it, but it's still not getting the number of death cases correctly.
> Fixed death count in Poland

- slovakia/src/main.js
more universal code than before
> SK edit .replace()

- malaysia/main.js
> fix malaysia

- slovakia/src/main.js
recovered data do not exist anymore in Slovakia
> source page changed and delete recovered

- slovakia/src/main.js
- Fixes for the new structure of currently scraped data
- Added data for counts of vaccinated and hospitalized
Resolves #293
> Slovakia - fix for new structure, additional data

- slovakia/package.json
- slovakia/src/main.js
Slovakia's "Updated at source" data is in a local format ("5. 3. 2021"), but we need to have it in the ISO string format to be able to properly parse it. This PR adds parsing of the source data and formatting it to the proper format to have it correctly in the output.
> Slovakia: Format "Updated at source" date to ISO string

- chile/main.js
> Change date selector

- chile/main.js
> Revert "Change date selector"

- estonia/Dockerfile
- estonia/package.json
- estonia/src/main.js
> [estonia] - update SDK, fix data parsing

- singapore/.gitignore
- singapore/package-lock.json
- singapore/package.json
- singapore/src/main.js
> singapore - source page changed
